### PR TITLE
Draft for Support Policy Changes

### PR DESCRIPTION
**Pull request by Ben-MyBB**
Current draft. Feel free to suggest changes.

### CODE REVIEW

**Comment by euantorano** [comment]
Some minor rewording and expanding of some points:

> Following [a recent discussion](https://community.mybb.com/thread-214047.html) that began within the community forums regarding relating to the current [Support Eligibility Policy](https://mybb.com/support/eligibility-policy/), we have decided to make some changes to how we provide support to users.
> 
> The Support Eligibiltiy Policy of old could be unclear in many circumstances and there were many edge cases and grey areas where it became unclear why a user may be denied official support. With the new changes, the policy will be vastly simplified and official support will only be denied for the following cases:
> 
> - Broadly illegal or unethical activity or content - including (but not limited to) the following:
>   - Unlawful distribution or redistribution of intellectual property or copyright content
>   - Propagating hateful content directed at specific groups or individuals
>   - Content and materials endagering the privacy, safety or security of others
>   
> For example, forums with the following kinds of content would be denied official support:
> 
> - "[warez](https://en.wikipedia.org/wiki/Warez)" - copyright content provided with copyright protections removed or subverted in some way - including providing cracked license keys for commercial software.
> - Forums allowing or condoning racist/sexist attacks against other individuals or groups
> - Forums providing "leaks" or dedicated to "[doxxing](http://www.dictionary.com/browse/dox)" individuals
> 
> Any users who run a board that breaches the new Support Eligibility Policy will retain the "denied support" marker publicly, allowing users to make a choice of their own whether they should provide support to that user.
> 
> In addition to these changes, staff members will not be chastised or penalised in any way for supporting users who have been denied support, though this is down to personal choice for staff members - they are not obligated to support anyone.
> 
> ## Users currently denied support
> 
> If you are currently denied support and believe that your forum doesn't breach the new Support Eligibility Policy, please get in contact with us by creating a new thread in the [Private Inquiries](http://community.mybb.com/forum-135.html) forum including the links to any forum(s) that you currently own. The team will review your site(s) and either revoke your denial or explain the reason for retaining the denial.
> 
> 
> We hope that these changes make the policy far more clear for everybody.

**Comment by dvz** [comment]
PR & Euan's content: proper names and their partial references should be capitalized (_Community Forums_, _the Team_, _the Policy_).

The [CoC](https://mybb.com/about/conduct/) can be referenced here, and and the denial reasons that are no longer in effect could also be listed.

**Comment by Ben-MyBB** [comment]
Will sort all of these, as I said on slack was just getting us a starting point.

**Comment by Ben-MyBB** [comment]
@euantorano PR updated

**Review by JordanMussi — CHANGES_REQUESTED** [review]
I've sent a PR to your fork with my proposed changes: Ben-MyBB/blog.mybb.com-drafts#1

**Comment by Ben-MyBB** [comment]
@JordanMussi Thanks for the changes, they are merged now :)

**Pull request merged**
